#!/bin/sh

pushd ~/.vim

curl -fLo core/plug/plug.vim https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

for d in plugged/*;
do
	pushd $d;
	git fetch origin;
	git reset --hard origin/master;
	popd;
done

popd
